#!/bin/bash
echo "Welcome to the ARCH Linux auto install script"
echo "choose your root filesystem disk"
ls -l /dev/sd* > disk.txt
ls -l /dev/nvme* > disks.txt
cat disks.txt
cat disk.txt
read root
echo "choose your efi partition"
cat disk.txt
cat disks.txt
read efi
echo "are you ready for the install"
echo "[Y|n]"
read yn1 
if [ yn1 == n ]
then
   echo "Aborting"
   exit
else
mount $root /mnt
pacstrap /mnt base linux linux-firmware vim nano
genfstab -U /mnt >> /mnt/etc/fstab
touch /mnt/efi.txt
echo $efi > /mnt/efi.txt
echo "ready to chroot into the directory"
echo "when you are in type ./continue"
cp continue /mnt
cp getmanagers /mnt
chmod +x /mnt/continue
chmod +x /mnt/getmanagers
arch-chroot /mnt
rm /mnt/continue
rm /mnt/getmanagers
rm -r /mnt/arch-display-managers
echo "INSTALLATION IS COMPLETE!"
fi
